= La gestion des dépendances
Xavier Bouclet
2017-04-11
:jbake-type: page
:jbake-tags: documentation, manual
:jbake-status: published

== Les dépendances

Un projet Maven est fait de dépendances. Ces dépendances sont de 2 types :

* directe
* transitive

=== Les dépendances directes

Une dépendance directe est définie dans le POM du projet à l'aide de la balise "dependency".

Voici l'exemple de déclaration de la dépendances à la librairie Junit.

[source,xml]
----
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.12</version>
</dependency>
----

Le groupId est l'identifiant unique parmis tous les projets.
L'artifactId ets le nom du jar sans la version.
La version indique la version de la dépendances qui est utilisée.

=== Les dépendances transitives

Une dépendance transitive est définie dans un des nombreux POM de l'arbre de dépendances.

Pour l'exemple de la librairie Junit, celle-ci vient avec son POM qui contient des dépendances suivantes :

[source,xml]
----
...
<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest-core</artifactId>
    <version>1.3</version>
</dependency>
...
----

Pour utiliser Junit, Maven va aussi télécharger hamcrest-core et potentiellement ces dépendances s'il y en a.

=== Le type

Par défaut une dépendance est de type jar mais il existe d'autres types de dépendances :

* pom : projet de description qui est généralement utiliser dans d'autres projets
* maven-plugin : type pour les plugin Maven
* ejb : une archive ejb
* war : une archive war
* ear : une archive ear
* rar : une archive rar
* par : une archive par (persitence pour ear)

=== Le scope

Le scope permet de définir quand le dépendance est nécessaire (compilation, runtime ...) :

* compile : la dépendance est toujours disponible dans le classpath.
* provided : la dépendance est nécessaire à la compilation mais est fournie par ailleurs (container, JDK...)
* runtime : la dépendance est nécessaire à l'exécution mais pas à la compilation.
* test : la dépendance est nécessaire à la compilation et à l'exécution des tests unitaires.

Lorsque rien n'est renseigné, Maven prend par défaut le scope compile.

== Les repositories

La grande question au sujet des dépendances, c'est comment Maven fait-il pour récupérer les dépendances.
La réponse est simple : il les télécharge.

Mais ou me direz-vous ?

Et bien c'est simple dans un repository de librairie.

=== Le repository Maven Central

Par défaut Maven utilise le repository dit central.

[source,xml]
----
<repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>Central Repository</name>
        <url>https://repo.maven.apache.org/maven2</url>
    </repository>
</repositories>
----

Ce repository est automatiquement défini dans Maven.
Il est tout à fait possible d'utiliser un autre repository en utilisant la balise "repository" vue plus haut.

=== Les autres

Il existe des tiers en dehors de Maven qui fournissent leur repository de manière publique.
Voici une liste de repositories qui sont accessibles :

* https://repository.jboss.org/[Jboss]
* http://repo.spring.io/release/[Spring]
* http://www.lutece.paris.fr/nexus/content/groups/maven_repository/[Mairie de Paris]
* https://maven.atlassian.com/repository/public/[Atlassian]

=== Le repository d'entreprise

Pour des raisons de sécurité et pour garder leurs librairies en interne, les entreprises font le choix d'avoir des repositories dits privés.
Ils sont accessibles uniquement sur le réseau de l'entreprise.

Voici une liste d'outils qui fournissent des repositories Maven une fois installés :

* Nexus
* Artifactory
* Archiva
